namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: string;
    NEXT_PUBLIC_FIREBASE_WEB_API_KEY: string;
    NEXT_PUBLIC_FIREBASE_DATABASE_URL: string;
    NEXT_PUBLIC_FIREBASE_USER_EMAIL: string;
    NEXT_PUBLIC_FIREBASE_USER_PASS: string;
    NEXT_PUBLIC_FIREBASE_PROJECT_ID: string;
  }
}